services:
  secret-backend:
    container_name: secret-backend
    build:
      context: ./secret-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./secret-backend/.env.production
    depends_on:
      - postgres

  secret-frontend:
    container_name: secret-frontend
    build:
      context: ./secret-frontend
      dockerfile: Dockerfile
    depends_on:
      - secret-backend
    ports:
      - 5174:5173
    env_file:
      - ./secret-frontend/.env.production

  postgres:
    image: postgres:15
    container_name: secret-postgres-db-prod
    restart: always
    ports:
      - 6543:5432
    volumes:
      - secret_service_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: secret-service-postgres-db

volumes:
  secret_service_postgres_data: